new update
jyoti-wp/klinic-project pull request #1
Opened 2020-03-13 14:56 UTC by jyoti-wp

Updated on feature branch

2020-03-13 14:58 UTC, imranhsayed requested changes

2020-03-13 14:58 UTC, imranhsayed commented on README.md
> +An Example of html project.
@jyoti-wp 
Please remove extra dot

2020-03-13 15:00 UTC, jyoti-wp commented on README.md
> +An Example of html project.
Thanks for the update

2020-03-13 15:01 UTC, imranhsayed commented on README.md
> +An Example of html project.
Your welcome

2020-04-25 15:09 UTC, imranhsayed requested changes

2020-04-25 15:09 UTC, imranhsayed commented on Klinic-hospital_files/magnific-popup.css
> +  font-family: Arial, Baskerville, monospace; }
Please give a  line below

2020-04-25 15:09 UTC, imranhsayed commented on html/index.html
> +			<img src="images/logo.png" alt="">
Please add alt text for accessibility for disable people like so :
`<img src="images/logo.png" alt="Logo">`

2020-04-25 15:09 UTC, imranhsayed commented on html/index.html
> +					<a class="" href="">HOME </a>
Remove extra space after Home.
Change the HOME to lowercase letters and use `text-transform:uppercase` to make it uppercase using css.

If there is not class name , remove `class=""`

2020-04-25 15:09 UTC, imranhsayed commented on html/index.html
> +			<img src="images/play-button.png" alt="play button"></a>
Please fix the indentation ( tabs and new line)

2020-04-25 15:09 UTC, imranhsayed commented on html/index.html
> +				<img src="images/4.jpg" alt="">
@jyoti-wp `alt` values  are missing

2020-04-25 15:09 UTC, imranhsayed commented on html/index.html
> +				<img src="images/1.png" alt="">
alt tag?

2020-04-25 15:09 UTC, imranhsayed commented on html/index.html
> +		</form>
`</button>` will go on a new line.
Please fix indentation

2020-04-25 15:09 UTC, imranhsayed commented on html/index.html
> +				<img src="images/1 (1).jpg" alt="admin">
image names should be separated using '-'
e.g. 
`<img src="images/1 (1).jpg" alt="admin">`
Should be :
`<img src="images-one.jpg" alt="admin">`

2020-04-25 15:09 UTC, imranhsayed commented on html/index.html
> +                    <a href="" class="bttn-mid btn-emt">Read More</a>
`href` value is missing.
Please put the value of `href` e.g.
` <a href="http://google.com" class="bttn-mid btn-emt">Read More</a>`

2020-04-28 15:01 UTC, merged